language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: cQfIvkC0o/NyEhFmYUd+17KiOj1onfGzLDWoxsYGMbM/XdHTBsaUOIHOnrejrhV3DL4I0z0a2oJYT1CU8Lpo20FRvLTRuiYe7juk3uaF5jDsSoALEDe7n5O1M3BvuoHRKH9nPXH4zfY/UULl1EA888MiJJ08ViUVzsSpaF7aSoNd5Tf9JUTk+MZ8zQFchKPKmmi6jkyVqDrFMFTzT2ePM7OykO3p/LcadG/4XFsIrjgA6TnonRq8Q0N61lbZlvOnCy65wmgzeSUsuvWqDdGLFz6nbO+NFK6T0ahxWlIlcGXbqD8rB6U6/SQOKBWnt65FIXRPgxsSE9mR39Xxoll5jXeB5TVCjvkoRNfqZg2Wsf5NS/gScJgCMUKa9K3jy5gxa0ZOYL271fFhGCF74wqDfrHcLScujzOj1+yqLKEzgJk1jr7HYJNGfEotuQqZ9EkzQv46ytOijAXF7FDfv+oJEK+W33/i7KwnLhB7ZLuMocfzjOx5QbrOZ0M+y2+ZiveH8hEU2+Ouyb+5xd38Nls3Ws81l9K2ZA0v0KW6qqGJCfpi/kGfZb1rKQ/afigMw1H2f6TVGb964i0hFOCC1+LZvEbR0lex8e/fMRtMpRj2QxTbRV+Yt5rzWKw4yc5kAOfgmqOBXewWVz/ngLXpkF6qos1hFte7UIanEz0Vt89m0TU=
  app: enigmatic-dusk-69852
  on:
    repo: pcmalinowski/netify
